2025-02-12 14:16:42,138 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 15 DataPulse
2025-02-12 14:17:02,854 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 DataPulse
2025-02-12 14:17:02,855 - WARNING  - Un avertissement - file_loader.py  - 10 DataPulse
2025-02-12 14:17:02,855 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 DataPulse
2025-02-12 14:28:16,201 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 DataPulse
2025-02-12 14:28:16,202 - WARNING  - Un avertissement - file_loader.py  - 10 DataPulse
2025-02-12 14:28:16,203 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 DataPulse
2025-02-12 14:28:31,731 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 DataPulse
2025-02-12 14:28:31,732 - WARNING  - Un avertissement - file_loader.py  - 10 DataPulse
2025-02-12 14:28:31,732 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 DataPulse
2025-02-12 14:29:06,168 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 DataPulse
2025-02-12 14:29:06,168 - WARNING  - Un avertissement - file_loader.py  - 10 DataPulse
2025-02-12 14:29:06,168 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 DataPulse
2025-02-12 14:30:20,340 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 DataPulse
2025-02-12 14:30:20,341 - WARNING  - Un avertissement - file_loader.py  - 10 DataPulse
2025-02-12 14:30:20,341 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 DataPulse
2025-02-12 14:30:31,288 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 DataPulse
2025-02-12 14:30:31,288 - WARNING  - Un avertissement - file_loader.py  - 10 DataPulse
2025-02-12 14:30:31,289 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 DataPulse
2025-02-12 14:35:03,712 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 - DataPulse
2025-02-12 14:35:03,713 - WARNING  - Un avertissement - file_loader.py  - 10 - DataPulse
2025-02-12 14:35:03,713 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 - DataPulse
2025-02-12 14:36:25,463 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 9 - DataPulse
2025-02-12 14:36:25,464 - WARNING  - Un avertissement - file_loader.py  - 10 - DataPulse
2025-02-12 14:36:25,464 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 11 - DataPulse
2025-02-12 14:38:14,633 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:38:14,634 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:38:14,635 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:40:20,731 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:40:20,732 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:40:20,732 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:42:58,365 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:42:58,366 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:42:58,366 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:43:16,499 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:43:16,499 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:43:16,499 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:43:37,062 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:43:37,062 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:43:37,063 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:44:02,997 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:44:02,998 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:44:02,998 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:44:26,447 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:44:26,447 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:44:26,447 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:44:45,405 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:44:45,405 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:44:45,406 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:45:14,234 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:45:14,235 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:45:14,235 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:45:53,097 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:45:53,098 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:45:53,098 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:47:11,832 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:47:11,832 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:47:11,833 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:47:59,265 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:47:59,265 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:47:59,265 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:48:07,462 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:48:07,462 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:48:07,462 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:49:21,775 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:49:21,776 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:49:21,776 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:50:54,450 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:50:54,451 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:50:54,451 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:52:14,608 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:52:14,608 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:52:14,608 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:52:56,814 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:52:56,814 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:52:56,815 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:53:22,534 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:53:22,534 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:53:22,534 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:53:51,841 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:53:51,841 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:53:51,841 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 14:55:24,939 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 14:55:24,941 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 14:55:24,941 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:01:44,127 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:01:44,128 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:01:44,128 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:02:05,652 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:02:05,653 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:02:05,653 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:02:23,014 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:02:23,014 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:02:23,014 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:09:03,629 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:09:03,630 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:09:03,630 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:10:53,247 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:10:53,249 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:10:53,249 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:11:04,425 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:11:04,425 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:11:04,425 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:11:39,379 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:11:39,379 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:11:39,380 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:19:44,523 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:19:44,524 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:19:44,524 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:22:52,588 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:22:52,590 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:22:52,590 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:23:26,144 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:23:26,144 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:23:26,145 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:23:49,342 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:23:49,342 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:23:49,343 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:24:05,056 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:24:05,056 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:24:05,057 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:25:26,252 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:25:26,253 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:25:26,253 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:26:33,457 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:26:33,459 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:26:33,460 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:27:46,686 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:27:46,687 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:27:46,687 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:32:58,184 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:32:58,185 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:32:58,185 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:33:03,999 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:33:03,999 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:33:03,999 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:39:17,028 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:39:17,030 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:39:17,030 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:41:09,449 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:41:09,451 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:41:09,451 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:41:42,747 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:41:42,748 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:41:42,748 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:42:37,921 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:42:37,922 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:42:37,922 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:42:50,020 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:42:50,021 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:42:50,021 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:43:56,827 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:43:56,830 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:43:56,830 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:44:13,500 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:44:13,501 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:44:13,502 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:44:57,967 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:44:57,969 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:44:57,970 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:45:09,590 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:45:09,590 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:45:09,591 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:45:47,829 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:45:47,831 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:45:47,831 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:46:10,626 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:46:10,626 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:46:10,626 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:46:19,941 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:46:19,941 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:46:19,941 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:46:42,785 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:46:42,785 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:46:42,785 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:47:16,259 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:47:16,259 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:47:16,259 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:47:39,732 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:47:39,733 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:47:39,733 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:47:55,251 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:47:55,251 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:47:55,251 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:49:48,476 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:49:48,477 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:49:48,477 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:50:03,030 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:50:03,031 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:50:03,031 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:50:58,082 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:50:58,082 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:50:58,082 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:51:16,353 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:51:16,354 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:51:16,355 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:51:33,291 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:51:33,291 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:51:33,292 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:51:39,302 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:51:39,303 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:51:39,303 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:51:50,138 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:51:50,139 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:51:50,139 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:56:42,605 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:56:42,606 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:56:42,606 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:56:55,642 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:56:55,643 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:56:55,643 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:58:00,303 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:58:00,304 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:58:00,304 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:58:15,951 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:58:15,951 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:58:15,952 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:59:16,433 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:59:16,435 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:59:16,435 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 15:59:55,906 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 15:59:55,908 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 15:59:55,909 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:00:21,926 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:00:21,927 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:00:21,927 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:02:24,552 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:02:24,552 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:02:24,552 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:02:59,701 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:02:59,703 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:02:59,703 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:04:43,256 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:04:43,257 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:04:43,257 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:05:05,757 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:05:05,758 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:05:05,758 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:11:54,144 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:11:54,146 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:11:54,146 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:12:03,077 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:12:03,077 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:12:03,077 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:12:48,575 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:12:48,575 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:12:48,575 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:13:50,909 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:13:50,910 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:13:50,910 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:15:37,358 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:15:37,361 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:15:37,361 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:15:45,115 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:15:45,115 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:15:45,115 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-12 16:18:03,395 - ERROR  - Ceci est une erreur suite à l'ajout entre éléments incompatibles - file_loader.py  - 11 - DataPulse
2025-02-12 16:18:03,398 - WARNING  - Un avertissement - file_loader.py  - 12 - DataPulse
2025-02-12 16:18:03,398 - CRITICAL  - Une erreur Critique !!! - file_loader.py  - 13 - DataPulse
2025-02-13 11:16:52,260 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 198 - DataPulse
2025-02-13 11:17:17,756 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 199 - DataPulse
2025-02-13 11:17:43,920 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 200 - DataPulse
2025-02-13 11:18:13,163 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 200 - DataPulse
2025-02-13 11:23:26,637 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 201 - DataPulse
2025-02-13 11:24:09,118 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 201 - DataPulse
2025-02-13 11:24:55,343 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 202 - DataPulse
2025-02-13 11:24:58,616 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 202 - DataPulse
2025-02-13 11:25:29,421 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 202 - DataPulse
2025-02-13 11:25:53,972 - ERROR  - Une erreur sévère s'est produite - file_loader.py  - 202 - DataPulse
2025-02-20 11:41:05,230 - ERROR  - Le fichier data/clients.csv n'existe pas. - utils.py  - 17 - DataPulse
2025-02-20 11:41:05,233 - ERROR  - Erreur dans le Module preview_file :Le fichier data/clients.csv n'existe pas  - preview.py  - 24 - DataPulse
2025-02-20 11:41:28,601 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 - DataPulse
2025-02-20 11:46:35,077 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 - DataPulse
2025-02-20 11:49:41,764 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 - DataPulse
2025-02-20 11:53:35,296 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 - DataPulse
2025-02-20 11:55:30,432 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 - DataPulse
2025-02-20 11:56:39,831 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 - DataPulse
2025-02-20 11:58:34,565 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 - DataPulse
2025-02-20 12:02:20,496 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 Lignes- DataPulse
2025-02-20 12:04:08,660 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 Lignes- DataPulse
2025-02-20 12:05:23,525 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 Lignes dans le fichier  - DataPulse
2025-02-20 12:05:38,293 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 36 Lignes dans le fichier  - DataPulse
2025-02-20 12:16:48,144 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 49 Lignes dans le fichier  - DataPulse
2025-02-20 12:23:00,138 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 49 Lignes dans le fichier  - DataPulse
2025-02-20 12:25:28,300 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 49 Lignes dans le fichier  - DataPulse
2025-02-20 12:26:29,791 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 49 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:02,869 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:02,881 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:02,896 - DEBUG  - Temps de chargement :0.013 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:02,896 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:39,883 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:39,885 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:39,891 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:39,892 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:54,165 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:54,166 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:54,172 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:30:54,172 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 12:31:39,480 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:31:39,480 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:31:39,487 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:31:39,488 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 12:32:22,960 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:32:22,961 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:32:22,968 - DEBUG  - Temps de chargement :0.007 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:32:22,968 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 12:33:32,048 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:33:32,049 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:33:32,058 - DEBUG  - Temps de chargement :0.008 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:33:32,058 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 12:34:16,506 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:34:16,507 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:34:16,513 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:34:16,513 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 12:35:40,319 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 12:35:40,321 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 12:35:40,327 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 12:35:40,327 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:31:10,812 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:31:10,814 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:31:10,821 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:31:10,821 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:32:39,964 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:32:39,966 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:32:39,972 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:32:39,973 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:33:17,053 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:33:17,054 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:33:17,060 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:33:17,060 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:37:44,626 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:37:44,628 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:37:44,637 - DEBUG  - Temps de chargement :0.007 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:37:44,638 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:38:41,932 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:38:41,932 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:38:41,938 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:38:41,939 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:44:29,969 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:44:29,971 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:46:43,427 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:46:43,429 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:46:43,435 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:46:43,436 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:50:57,142 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:50:57,144 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:54:45,967 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:54:45,968 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:39,307 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:39,309 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:39,315 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:39,315 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:48,128 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:48,128 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:48,135 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:48,135 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:56,956 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:56,957 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:56,964 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:56:56,964 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:02,868 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:02,868 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:02,874 - DEBUG  - Temps de chargement :0.005 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:02,874 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:27,027 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:27,027 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:27,033 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:27,033 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:44,062 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:44,063 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:44,069 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:44,069 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:54,363 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:54,363 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:54,369 - DEBUG  - Temps de chargement :0.005 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 13:57:54,369 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 14:53:08,421 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 14:53:08,432 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 14:53:39,144 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 14:53:39,153 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 14:53:50,543 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 14:53:50,553 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 14:54:00,747 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 14:54:00,757 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 14:54:18,350 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 14:54:18,360 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 14:59:21,413 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 14:59:21,425 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 14:59:28,878 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 14:59:28,888 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:04:04,140 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 15:04:04,149 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:04:51,213 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 15:04:51,223 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:07:31,865 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 15:07:31,875 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:25:41,029 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 15:25:41,041 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:28,513 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:28,515 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:28,521 - DEBUG  - Temps de chargement :0.005 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:28,521 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:28,524 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:43,348 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:43,349 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:43,355 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:43,355 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 15:27:43,358 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:28:05,669 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 15:28:05,670 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 50 Lignes dans le fichier  - DataPulse
2025-02-20 15:28:05,676 - DEBUG  - Temps de chargement :0.005 sec - utils.py  - 54 Lignes dans le fichier  - DataPulse
2025-02-20 15:28:05,676 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 55 Lignes dans le fichier  - DataPulse
2025-02-20 15:28:05,680 - INFO  -  - utils.py  - 76 Lignes dans le fichier  - DataPulse
2025-02-20 15:36:40,979 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 48 Lignes dans le fichier  - DataPulse
2025-02-20 15:36:40,989 - INFO  - 83 lignes trouvées après filtrage - utils.py  - 74 Lignes dans le fichier  - DataPulse
2025-02-20 15:37:03,555 - DEBUG  - Mode verbose activé - utils.py  - 18 Lignes dans le fichier  - DataPulse
2025-02-20 15:37:03,555 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 48 Lignes dans le fichier  - DataPulse
2025-02-20 15:37:03,561 - DEBUG  - Temps de chargement :0.006 sec - utils.py  - 52 Lignes dans le fichier  - DataPulse
2025-02-20 15:37:03,561 - DEBUG  - Nombre de ligne chargées : 1000 - utils.py  - 53 Lignes dans le fichier  - DataPulse
2025-02-20 15:37:03,565 - INFO  - 97 lignes trouvées après filtrage - utils.py  - 74 Lignes dans le fichier  - DataPulse
2025-02-20 15:37:08,733 - INFO  - Le type de fichier détecté est : CSV - utils.py  - 48 Lignes dans le fichier  - DataPulse
2025-02-20 15:37:08,742 - INFO  - 97 lignes trouvées après filtrage - utils.py  - 74 Lignes dans le fichier  - DataPulse
2025-02-20 23:31:31,057 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:31:31,065 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:20,059 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:20,059 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:20,065 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:20,065 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:20,065 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:30,123 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:30,129 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:37,381 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:37,382 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:37,387 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:37,387 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-20 23:32:37,387 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:33:36,256 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-20 23:33:36,256 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:33:36,262 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-20 23:33:36,262 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-20 23:33:36,262 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:34:35,917 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-20 23:34:35,918 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:34:35,924 - DEBUG - Temps de chargement: 0.006 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-20 23:34:35,925 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-20 23:34:35,925 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:34:47,207 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:34:47,212 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:35:06,719 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:35:06,729 - INFO - 97 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-20 23:35:06,729 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-20 23:35:27,478 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-20 23:35:27,487 - INFO - 85 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-20 23:35:27,488 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-21 12:25:37,042 - ERROR - Le fichier fourni /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/server_logs.txt ne peut être traité à cause de l'erreur : [Errno 2] No such file or directory: '/home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/server_logs.txt' - data_summary.py - 65 Lignes dans le Fichier : - DataPulse
2025-02-21 12:25:42,815 - ERROR - Le fichier fourni /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/server_logs.txt ne peut être traité à cause de l'erreur : [Errno 2] No such file or directory: '/home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/server_logs.txt' - data_summary.py - 65 Lignes dans le Fichier : - DataPulse
2025-02-21 12:26:29,156 - ERROR - Le fichier fourni /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/server_logs.txt ne peut être traité à cause de l'erreur : [Errno 2] No such file or directory: '/home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/server_logs.txt' - data_summary.py - 65 Lignes dans le Fichier : - DataPulse
2025-02-22 20:19:35,713 - ERROR - Le fichier DataPulse/data/clients.csv n'existe pas - utils.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-22 20:19:35,716 - ERROR - Erreur dans preview_file: Le fichier DataPulse/data/clients.csv n'existe pas - preview.py - 31 Lignes dans le Fichier : - DataPulse
2025-02-22 20:21:00,342 - ERROR - Le fichier DataPulse/data/clients.csv n'existe pas - utils.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-22 20:21:00,344 - ERROR - Erreur dans preview_file: Le fichier DataPulse/data/clients.csv n'existe pas - preview.py - 31 Lignes dans le Fichier : - DataPulse
2025-02-22 20:28:45,004 - ERROR - Le fichier DataPulse/data/clients.csv n'existe pas - utils.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-22 20:28:45,006 - ERROR - Erreur dans preview_file: Le fichier DataPulse/data/clients.csv n'existe pas - preview.py - 31 Lignes dans le Fichier : - DataPulse
2025-02-22 20:33:53,111 - ERROR - Le fichier /data/clients.csv n'existe pas - utils.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-22 20:33:53,113 - ERROR - Erreur dans preview_file: Le fichier /data/clients.csv n'existe pas - preview.py - 31 Lignes dans le Fichier : - DataPulse
2025-02-22 20:34:00,028 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:34:00,035 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:34:03,109 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:34:03,115 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:34:52,293 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:34:52,300 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:38:06,777 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:38:06,784 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:38:33,846 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 20:38:33,847 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:38:33,854 - DEBUG - Temps de chargement: 0.006 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 20:38:33,854 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 20:38:33,854 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:39:44,316 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:39:44,325 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:39:49,167 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 20:39:49,168 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:39:49,173 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 20:39:49,173 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 20:39:49,174 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:40:06,736 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 20:40:06,737 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:40:06,742 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 20:40:06,742 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 20:40:06,742 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:40:38,870 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:40:38,878 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:41:34,107 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:41:34,114 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:41:59,952 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:41:59,961 - INFO - 97 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-22 20:41:59,961 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:42:07,562 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:42:07,570 - INFO - 83 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-22 20:42:07,571 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 20:42:15,095 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 20:42:15,103 - INFO - 97 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-22 20:42:15,103 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:31,879 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:31,889 - INFO - 97 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:31,890 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:54,219 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:54,219 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:54,224 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:54,224 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:30:54,224 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:32:34,434 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:32:34,442 - INFO - 83 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-22 21:32:34,444 - INFO - 💾 Résultats enregistrés dans 'resultats.txt'. - utils.py - 115 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:29,845 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:29,845 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:29,850 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:29,850 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:29,850 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:40,028 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:40,029 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:40,035 - DEBUG - Temps de chargement: 0.006 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:40,035 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:33:40,035 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:03,563 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:03,563 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:03,569 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:03,569 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:03,569 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:13,613 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:13,620 - INFO - 83 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-22 21:34:13,622 - INFO - 💾 Résultats enregistrés dans 'resultats.txt'. - utils.py - 115 Lignes dans le Fichier : - DataPulse
2025-02-22 21:44:47,818 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:44:47,818 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:44:47,824 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:44:47,824 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:44:47,824 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:47:32,009 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:47:32,009 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:47:32,015 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:47:32,015 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:47:32,015 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:12,692 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:12,692 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:12,697 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:12,697 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:12,698 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:18,762 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:18,762 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:18,767 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:18,767 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:18,767 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:35,305 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:35,305 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:35,311 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:35,311 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:54:35,311 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:55:12,261 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:55:12,261 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:55:12,266 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:55:12,266 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:55:12,267 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 21:57:56,018 - ERROR - Le fichier data/clients.csv n'existe pas - utils.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-22 21:57:56,019 - ERROR - Erreur dans preview_file: Le fichier data/clients.csv n'existe pas - preview.py - 30 Lignes dans le Fichier : - DataPulse
2025-02-22 21:58:12,633 - ERROR - Le fichier data/clients.csv n'existe pas - utils.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-22 21:58:12,633 - ERROR - Erreur dans preview_file: Le fichier data/clients.csv n'existe pas - preview.py - 30 Lignes dans le Fichier : - DataPulse
2025-02-22 21:59:33,688 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 21:59:33,689 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 21:59:33,694 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 21:59:33,694 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 21:59:33,694 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 22:00:43,499 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 22:00:43,499 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 22:00:43,504 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 22:00:43,504 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 22:00:43,505 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:16,592 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:16,600 - INFO - 83 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:16,601 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:47,208 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:47,209 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:47,214 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:47,214 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 22:01:47,214 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-22 22:02:42,731 - DEBUG - Mode verbose activé - utils.py - 17 Lignes dans le Fichier : - DataPulse
2025-02-22 22:02:42,731 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-22 22:02:42,737 - DEBUG - Temps de chargement: 0.005 sec - utils.py - 58 Lignes dans le Fichier : - DataPulse
2025-02-22 22:02:42,737 - DEBUG - Nombres de lignes chargées: 1000 - utils.py - 59 Lignes dans le Fichier : - DataPulse
2025-02-22 22:02:42,737 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-24 20:45:29,102 - ERROR - Erreur lecture fichier json /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/data/transactions.json; Extra data: line 12 column 6 (char 319) - file_loaders.py - 65 Lignes dans le Fichier : - DataPulse
2025-02-27 21:29:34,779 - ERROR - Le fichier /data/clients.csv n'existe pas - utils.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-27 21:29:34,782 - ERROR - Erreur dans preview_file: Le fichier /data/clients.csv n'existe pas - preview.py - 30 Lignes dans le Fichier : - DataPulse
2025-02-27 21:32:38,541 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-27 21:32:38,810 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-27 21:32:45,606 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-27 21:32:45,876 - INFO - Apercu des données - utils.py - 95 Lignes dans le Fichier : - DataPulse
2025-02-27 21:33:01,266 - INFO - Type detecté : CSV  - utils.py - 49 Lignes dans le Fichier : - DataPulse
2025-02-27 21:33:01,729 - INFO - 5033 lignes trouvées après filtrage - utils.py - 84 Lignes dans le Fichier : - DataPulse
2025-02-27 21:33:01,783 - INFO - 💾 Résultats enregistrés dans 'resultats.txt'. - utils.py - 115 Lignes dans le Fichier : - DataPulse
2025-02-27 23:35:28,735 - ERROR - Le fichier /data/clients.csv n'existe pas - utils.py - 27 Lignes dans le Fichier : - DataPulse
2025-02-27 23:35:28,737 - ERROR - Erreur dans preview_file: Le fichier /data/clients.csv n'existe pas - preview.py - 30 Lignes dans le Fichier : - DataPulse
2025-02-27 23:35:34,925 - INFO - Type detecté : CSV  - utils.py - 48 Lignes dans le Fichier : - DataPulse
2025-02-27 23:35:35,202 - INFO - Apercu des données - utils.py - 94 Lignes dans le Fichier : - DataPulse
2025-02-27 23:40:31,486 - ERROR - Le fichier data/clients.csv n'existe pas - utils.py - 27 Lignes dans le Fichier : - DataPulse
2025-02-27 23:40:31,489 - ERROR - Erreur dans preview_file: Le fichier data/clients.csv n'existe pas - preview.py - 30 Lignes dans le Fichier : - DataPulse
2025-02-27 23:40:45,633 - INFO - Type detecté : CSV  - utils.py - 48 Lignes dans le Fichier : - DataPulse
2025-02-27 23:40:45,933 - INFO - Apercu des données - utils.py - 94 Lignes dans le Fichier : - DataPulse
2025-02-27 23:47:24,487 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:47:51,297 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:49:17,820 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:50:34,868 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:53:46,114 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:58:01,419 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:59:04,605 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:59:34,380 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-27 23:59:35,223 - ERROR - Erreur dans analyse: object of type 'NoneType' has no len() - analyse.py - 30 Lignes dans le Fichier : - DataPulse
2025-02-28 00:00:17,087 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 00:00:17,949 - ERROR -  Erreur lors de l'enregistrement des résultats : 'NoneType' object is not iterable - utils.py - 116 Lignes dans le Fichier : - DataPulse
2025-02-28 00:02:19,944 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 00:02:20,844 - ERROR -  Erreur lors de l'enregistrement des résultats : 'NoneType' object is not iterable - utils.py - 116 Lignes dans le Fichier : - DataPulse
2025-02-28 00:02:20,845 - ERROR - Erreur dans analyse: 'NoneType' object is not iterable - analyse.py - 26 Lignes dans le Fichier : - DataPulse
2025-02-28 00:02:20,845 - ERROR - Erreur dans analyse: object of type 'NoneType' has no len() - analyse.py - 33 Lignes dans le Fichier : - DataPulse
2025-02-28 08:24:52,649 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 08:25:17,855 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 08:25:18,664 - ERROR -  Erreur lors de l'enregistrement des résultats : 'NoneType' object is not iterable - utils.py - 116 Lignes dans le Fichier : - DataPulse
2025-02-28 08:25:18,665 - ERROR - Erreur dans analyse: 'NoneType' object is not iterable - analyse.py - 29 Lignes dans le Fichier : - DataPulse
2025-02-28 08:25:18,665 - ERROR - Erreur dans analyse: object of type 'NoneType' has no len() - analyse.py - 36 Lignes dans le Fichier : - DataPulse
2025-02-28 08:25:51,262 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 08:25:52,058 - ERROR -  Erreur lors de l'enregistrement des résultats : 'NoneType' object is not iterable - utils.py - 116 Lignes dans le Fichier : - DataPulse
2025-02-28 08:25:52,058 - ERROR - Erreur dans analyse: 'NoneType' object is not iterable - analyse.py - 29 Lignes dans le Fichier : - DataPulse
2025-02-28 08:26:10,189 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 08:26:49,811 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 08:26:50,608 - ERROR - Erreur dans analyse: 'NoneType' object is not iterable - analyse.py - 29 Lignes dans le Fichier : - DataPulse
2025-02-28 08:27:20,145 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 08:27:20,982 - ERROR - Erreur dans analyse: 'NoneType' object is not iterable - analyse.py - 29 Lignes dans le Fichier : - DataPulse
2025-02-28 09:22:53,261 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 09:22:54,417 - ERROR - Erreur dans analyse: En écrivant dans le fichier -  'NoneType' object is not iterable - analyse.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-28 10:03:36,469 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:23:38,267 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:24:21,256 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:24:50,579 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:26:19,987 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:26:20,792 - ERROR - Erreur dans analyse: En écrivant dans le fichier -  can only concatenate str (not "int") to str - analyse.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-28 21:26:52,786 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:26:53,592 - ERROR - Erreur dans analyse: En écrivant dans le fichier -  can only concatenate str (not "int") to str - analyse.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-28 21:27:11,950 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:27:12,744 - ERROR - Erreur dans analyse: En écrivant dans le fichier -  unsupported operand type(s) for +: 'int' and 'str' - analyse.py - 28 Lignes dans le Fichier : - DataPulse
2025-02-28 21:28:01,600 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:28:02,392 - ERROR - Erreur dans analyse: En écrivant dans le fichier -  unsupported operand type(s) for +: 'int' and 'str' - analyse.py - 29 Lignes dans le Fichier : - DataPulse
2025-02-28 21:30:06,800 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:30:52,926 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:31:52,244 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:32:54,195 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:34:57,468 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:44:46,701 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:45:23,750 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:46:50,669 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-02-28 21:47:02,790 - INFO - NumExpr defaulting to 4 threads. - utils.py - 161 Lignes dans le Fichier : - numexpr.utils
2025-03-06 14:53:55,999 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 14:53:56,054 - WARNING - Graphique ignoré : plot_inactive_clients (aucune donnée) - base_visualizer.py - 50 Lignes dans le Fichier : - DataPulse
2025-03-06 14:53:56,118 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:23:32,622 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:23:32,743 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:23:32,769 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:23:32,856 - INFO - Graphiquie 'Client inactifs' Générés - client_visualizer.py - 78 Lignes dans le Fichier : - DataPulse
2025-03-06 15:23:33,110 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:26:59,728 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:26:59,834 - ERROR - Erreur lors de la création du graphique 'CLients inactifs' : Could not interpret value `Mois` for `hue`. Value is a string, but `data` was not passed. - client_visualizer.py - 81 Lignes dans le Fichier : - DataPulse
2025-03-06 15:26:59,835 - WARNING - Graphique ignoré : plot_inactive_clients (aucune donnée) - base_visualizer.py - 50 Lignes dans le Fichier : - DataPulse
2025-03-06 15:26:59,920 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:29:56,126 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:29:56,213 - ERROR - Erreur lors de la création du graphique 'CLients inactifs' : Could not interpret value `Mois` for `hue`. Value is a string, but `data` was not passed. - client_visualizer.py - 81 Lignes dans le Fichier : - DataPulse
2025-03-06 15:29:56,213 - WARNING - Graphique ignoré : plot_inactive_clients (aucune donnée) - base_visualizer.py - 50 Lignes dans le Fichier : - DataPulse
2025-03-06 15:29:56,280 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:30:24,744 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:30:24,877 - ERROR - Erreur lors de la création du graphique 'CLients inactifs' : Could not interpret value `Mois` for `hue`. Value is a string, but `data` was not passed. - client_visualizer.py - 81 Lignes dans le Fichier : - DataPulse
2025-03-06 15:30:24,877 - WARNING - Graphique ignoré : plot_inactive_clients (aucune donnée) - base_visualizer.py - 50 Lignes dans le Fichier : - DataPulse
2025-03-06 15:30:24,966 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:33:50,733 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:33:50,739 - ERROR - Erreur lors de la création du graphique 'CLients inactifs' : 'coolwarn' is not a valid palette name - client_visualizer.py - 81 Lignes dans le Fichier : - DataPulse
2025-03-06 15:33:50,853 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:33:50,997 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:33:51,002 - ERROR - Erreur lors de la création du graphique 'CLients inactifs' : 'coolwarn' is not a valid palette name - client_visualizer.py - 81 Lignes dans le Fichier : - DataPulse
2025-03-06 15:33:51,003 - WARNING - Graphique ignoré : plot_inactive_clients (aucune donnée) - base_visualizer.py - 50 Lignes dans le Fichier : - DataPulse
2025-03-06 15:33:51,071 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:36:07,128 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:36:07,134 - ERROR - Erreur lors de la création du graphique 'CLients inactifs' : 'coolwarn' is not a valid palette name - client_visualizer.py - 81 Lignes dans le Fichier : - DataPulse
2025-03-06 15:36:07,245 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:36:07,338 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:36:07,343 - ERROR - Erreur lors de la création du graphique 'CLients inactifs' : 'coolwarn' is not a valid palette name - client_visualizer.py - 81 Lignes dans le Fichier : - DataPulse
2025-03-06 15:36:07,344 - WARNING - Graphique ignoré : plot_inactive_clients (aucune donnée) - base_visualizer.py - 50 Lignes dans le Fichier : - DataPulse
2025-03-06 15:36:07,431 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:36:37,538 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:36:37,690 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:36:37,757 - INFO - Graphiquie 'Client inactifs' Générés - client_visualizer.py - 78 Lignes dans le Fichier : - DataPulse
2025-03-06 15:39:28,500 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:39:28,724 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:39:28,821 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:39:28,911 - INFO - Graphiquie 'Client inactifs' Générés - client_visualizer.py - 78 Lignes dans le Fichier : - DataPulse
2025-03-06 15:39:29,080 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 15:49:23,407 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:49:23,450 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:49:23,538 - INFO - Graphiquie 'Client inactifs' Générés - client_visualizer.py - 78 Lignes dans le Fichier : - DataPulse
2025-03-06 15:51:59,526 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 15:52:00,161 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:52:00,332 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 15:52:00,485 - INFO - Graphiquie 'Client inactifs' Générés - client_visualizer.py - 78 Lignes dans le Fichier : - DataPulse
2025-03-06 15:52:00,737 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
2025-03-06 22:24:55,399 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 22:24:55,434 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 22:24:55,486 - INFO - Graphiquie 'Client inactifs' Générés - client_visualizer.py - 78 Lignes dans le Fichier : - DataPulse
2025-03-06 22:26:11,441 - INFO - Graphique 'Répartition des clients' généré. - client_visualizer.py - 56 Lignes dans le Fichier : - DataPulse
2025-03-06 22:26:11,615 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 22:26:11,654 - INFO - Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting. - category.py - 224 Lignes dans le Fichier : - matplotlib.category
2025-03-06 22:26:11,721 - INFO - Graphiquie 'Client inactifs' Générés - client_visualizer.py - 78 Lignes dans le Fichier : - DataPulse
2025-03-06 22:26:11,967 - INFO - Rapport PDF généré : /home/ratel/BigDataPython/cours_Greta_python/code_python/DataPulse/DataPulse/reports/clients_report.pdf - base_visualizer.py - 57 Lignes dans le Fichier : - DataPulse
